theme: jekyll-theme-minimal
github:
  is_project_page: false
title: Games Plaza
description: 
  Welcome to Games Plaza! Find any and all games here for free, with no strings attached and no viruses. All of our programs are manually tested by our testers. 
